gc-service:
  username-validator-url: ${GC_VALIDATOR_URL}
  listing-url: ${GC_LISTING_URL}

okta:
  oauth2:
    domain: gc-connect.eu.auth0.com
    issuer: https://gc-connect.eu.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    token-url: https://gc-connect.eu.auth0.com/oauth/token
    api-url: https://gc-connect.eu.auth0.com/api/v2/
    connection: Username-Password-Authentication

spring:
  data:
    mongodb:
      database: gc-connect
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWD}@${MONGO_CLUSTER}.mongodb.net/?retryWrites=true&w=majority&appName=gc-connect



logging:
  level:
    ROOT: INFO
    pl.zdna.gcconnect: DEBUG
    org:
      springframework:
        boot:
          spring-boot-autoconfigure: ERROR